sudo: required
services:
  - docker
language: node_js

before_install:
  - docker build -t mtahakhan/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run mtahakhan/react-test npm test -- --coverage

after_success:
  - docker build -t mtahakhan/multi-client ./client
  - docker build -t mtahakhan/multi-nginx ./nginx
  - docker build -t mtahakhan/multi-server ./server
  - docker build -t mtahakhan/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mtahakhan/multi-client
  - docker push mtahakhan/multi-nginx
  - docker push mtahakhan/multi-server
  - docker push mtahakhan/multi-worker
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh #installed heroku CLI
  - heroku plugins:install @heroku-cli/plugin-container-registry
  - docker login -u "mtahakhan" --password=$(heroku auth:token) registry.heroku.com #logged in
  - heroku container:push web --app docker-fibserires
  - heroku container:release web --app docker-fibserires
